config/routes.rb
Rails.application.routes.draw do
  get 'main/login'
  post 'main/create'
  get 'main/destroy'
  get 'main/user_items'
  get 'main/inventories'
  get 'shop/:id', to: 'shop#main', as: 'shop_main'
  post 'shop/:id/:bid/buy', to: 'shop#buy', as: 'shop_buy'
  resources :inventories
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :item ,dependent: :destroy
	has_many :inventory ,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private
		def is_login?
			return session[:logged_in] == true
		end

		def must_be_logged_in
			if is_login?
				return true
			else
				redirect_to main_login_path, notice: 'you must login before accessing this page'
			end
		end
		def reset_edit_session
			pp session.to_h
			session[:edit]=false
		end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:price, :user_id, :item_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :reset_edit_session

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    session[:edit] = true
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:user_id, :price, :name, :stock)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login
  end

  def create
    u = User.where(login: params[:login]).first
    if u && u.authenticate(params[:password])
      redirect_to main_user_items_path
      session[:logged_in] = true
      session[:user] = u.id
    else
      redirect_to main_login_path, notice: 'wrong login or password'
    end
  end

  def destroy
    reset_session
  end

  def user_items
    must_be_logged_in
    u = session[:user]
    @db = Item.where(user_id: u)
  end

  def inventories
    must_be_logged_in
    u = session[:user]
    @db = Inventory.where(user_id: u)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
	def main
		@db = Item.where(user_id: params[:id])
	end

	def buy
		@item = Item.where(id: params[:id])
		if @item[0].stock.to_i > 0
			@item[0].stock -= 1
			@item[0].save
			inventory = Inventory.new
			inventory.user_id = session[:user]
			inventory.item_id = params[:id]
			inventory.price = @item[0].price
			inventory.timestamp = Time.now
			inventory.save
			redirect_to shop_main_path(params[:bid]),notice: 'buy item success'
		else
			redirect_to shop_main_path(params[:bid]),notice: 'out of order'
		end
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price,step: :any%>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.text_field :item_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>Price:</strong>
    <%= inventory.price %>
  </p>

  <p>
    <strong>User:</strong>
    <%= inventory.user_id %>
  </p>

  <p>
    <strong>Item:</strong>
    <%= inventory.item_id %>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventories</h1>

<div id="inventories">
  <% @inventories.each do |inventory| %>
    <%= render inventory %>
    <p>
      <%= link_to "Show this inventory", inventory %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory", new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Edit this inventory", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to inventories", inventories_path %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%if !session[:edit]  %>
  <div>
    <%= form.label :user_id, style: "display: block" , class: 'form-label'%>
    <%= form.text_field :user_id , class: 'form-control'%>
  </div>
  <%end%>

  <div>
    <%= form.label :price, style: "display: block" , class: 'form-label'%>
    <%= form.number_field :price,step: :any, class: 'form-control'%>
  </div>

  <div>
    <%= form.label :name, style: "display: block", class: 'form-label' %>
    <%= form.text_field :name , class: 'form-control'%>
  </div>

  <div>
    <%= form.label :stock, style: "display: block", class: 'form-label' %>
    <%= form.number_field :stock , class: 'form-control'%>
  </div>

  <div>
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>User:</strong>
    <%= item.user_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= item.stock %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lec102</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <% flash.each do |type,msg| %>
        <p>
          <%= msg %>
        </p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/create.html.erb
<h1>Main#create</h1>
<p>Find me in app/views/main/create.html.erb</p>

app/views/main/destroy.html.erb
<h1>Main#destroy</h1>
<p>Find me in app/views/main/destroy.html.erb</p>

<h2> logout already </h2>

app/views/main/inventories.html.erb
<h1>Inventories</h1>
<%= @temp %>
<table class="table">
  <tr>
    <th></th>
    <th>Price</th>
    <th>Seller</th>
  </tr>
  <% i = 1 %>
  <% for data in @db %>
    <tr>
      <td><%= i %></td>
      <td><%= data.price %></td>
      <td><%= Item.where(id: data.item_id)[0].user_id %></td>
      <% i+=1 %>
    </tr>
  <% end %>
</table>

app/views/main/login.html.erb
<h1>Main#login</h1>
<%= form_with url: main_create_path, data: {turbo: false} do |f| %>
	<p>
		<%= f.label :login, class: 'form-label'%>
		<%= f.text_field :login, class: 'form-control'%>
	</p>
	<p>
		<%= f.label :password, class: 'form-label' %>
		<%= f.password_field :password, class: 'form-control' %>
	</p>
	<br>
	<%= f.submit :OK , class: 'btn btn-primary'%>
<% end %>

app/views/main/user_items.html.erb
<h1>Main#user_items</h1>
<%= @temp %>
<table class="table">
  <tr>
    <th></th>
    <th>Price</th>
    <th>Name</th>
    <th>Stock</th>
    <th></th>
    <th></th>
  </tr>
  <% i = 1 %>
  <% for data in @db %>
    <tr>
      <td><%= i %></td>
      <td><%= data.price %></td>
      <td><%= data.name %></td>
      <td><%= data.stock %></td>
      <td><%= button_to('edit',edit_item_path(data.id),method: :get, class: 'btn btn-primary') %></td>
      <td><%= button_to('delete', item_path(data.id), method: :delete, class: 'btn btn-primary') %></td>
      <% i+=1 %>
    </tr>
  <% end %>
</table>
<%= button_to('new', new_item_path, method: :get, class: 'btn btn-primary') %>

app/views/shop/buy.html.erb
<h1>Buy</h1>

app/views/shop/main.html.erb
<%= @temp %>
<table class="table">
  <tr>
    <th></th>
    <th>Price</th>
    <th>Name</th>
    <th>Stock</th>
    <% if session[:logged_in] == true %><th></th><% end %>
  </tr>
  <% i = 1 %>
  <% for data in @db %>
    <tr>
      <td><%= i %></td>
      <td><%= data.price %></td>
      <td><%= data.name %></td>
      <td><%= data.stock %></td>
      <% if session[:logged_in] == true %>
      	<td><%= button_to('buy',shop_buy_path(data.id,params[:id]),class: 'btn btn-primary') %></td>
      <% end %>
      <% i+=1 %>
    </tr>
  <% end %>
</table>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :login, style: "display: block" %>
    <%= form.text_field :login %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Login:</strong>
    <%= user.login %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>